name: fast lint checks
on:
    pull_request:
        types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify-labels:
    name: verify labels
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            disable-reviews: true
            valid-labels: 'bug, feature, security, maintenance, documentation, dependencies'
